"""added google_id, auth_provider, and made hashed_password optional

Revision ID: 35a3f40ca3db
Revises: 46c22178e26d
Create Date: 2025-10-08 00:15:03.384819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # NEW


# revision identifiers, used by Alembic.
revision: str = '35a3f40ca3db'
down_revision: Union[str, None] = '46c22178e26d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outstandingtoken', 'token')
    op.add_column('user', sa.Column('google_id', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False))
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'user', ['google_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'auth_provider')
    op.drop_column('user', 'google_id')
    op.add_column('outstandingtoken', sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
