"""added a model for JWT

Revision ID: af06f7c50116
Revises: ba0731fa7242
Create Date: 2025-09-26 21:49:33.797582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # NEW


# revision identifiers, used by Alembic.
revision: str = 'af06f7c50116'
down_revision: Union[str, None] = 'ba0731fa7242'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('access', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('refresh', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jwt')
    # ### end Alembic commands ###
