"""provided a default value for auth_provider

Revision ID: b0225c07cc50
Revises: 35a3f40ca3db
Create Date: 2025-10-10 22:19:19.580353

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel  # NEW
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b0225c07cc50"
down_revision: Union[str, None] = "35a3f40ca3db"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Set the default value for the column
    op.alter_column(
        "user",
        "auth_provider",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "auth_provider",
        existing_type=sa.VARCHAR(length=50),
        server_default=None,
        nullable=True,
    )
    # ### end Alembic commands ###
