"""Added created_at to Skill model

Revision ID: d32c87f7bafe
Revises: b0225c07cc50
Create Date: 2025-12-07 21:16:15.864927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # NEW


# revision identifiers, used by Alembic.
revision: str = 'd32c87f7bafe'
down_revision: Union[str, None] = 'b0225c07cc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profile', 'avatar_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.add_column('skill', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'created_at')
    op.alter_column('profile', 'avatar_url',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
